# Generated by Django 3.2.6 on 2021-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestellung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='piece',
            field=models.IntegerField(default=0),
        ),
    ]
